
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package modelo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 28;
  public static final int ID_VAR = 15;
  public static final int DISTINTO = 19;
  public static final int PROG_FIN = 5;
  public static final int ASIGNA_TIPO = 17;
  public static final int ASIGNA_VAR = 16;
  public static final int RESTA = 27;
  public static final int COR_CIERRA = 35;
  public static final int PROG_COMIENZO = 4;
  public static final int WRITE = 7;
  public static final int PAR_ABRE = 30;
  public static final int AND = 24;
  public static final int IGUAL = 18;
  public static final int COR_ABRE = 34;
  public static final int MULTIPLICA = 29;
  public static final int OR = 25;
  public static final int SUMA = 26;
  public static final int CONST_FLOAT = 13;
  public static final int IF = 8;
  public static final int PUNTO_COMA = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SEC_COMIENZO = 2;
  public static final int COMA = 37;
  public static final int MENOR = 20;
  public static final int TIPO_DATO = 11;
  public static final int LLAVE_ABRE = 32;
  public static final int MAYOR = 22;
  public static final int ELSE = 9;
  public static final int POSITION = 6;
  public static final int SEC_FIN = 3;
  public static final int WHILE = 10;
  public static final int MAYOR_IGUAL = 23;
  public static final int LLAVE_CIERRA = 33;
  public static final int CONST_STR = 14;
  public static final int MENOR_IGUAL = 21;
  public static final int PAR_CIERRA = 31;
  public static final int CONST_INT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEC_COMIENZO",
  "SEC_FIN",
  "PROG_COMIENZO",
  "PROG_FIN",
  "POSITION",
  "WRITE",
  "IF",
  "ELSE",
  "WHILE",
  "TIPO_DATO",
  "CONST_INT",
  "CONST_FLOAT",
  "CONST_STR",
  "ID_VAR",
  "ASIGNA_VAR",
  "ASIGNA_TIPO",
  "IGUAL",
  "DISTINTO",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "SUMA",
  "RESTA",
  "DIVIDE",
  "MULTIPLICA",
  "PAR_ABRE",
  "PAR_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COR_ABRE",
  "COR_CIERRA",
  "PUNTO_COMA",
  "COMA"
  };
}

